name: Check Dependencies

on: pull_request
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Grant permission
        run: chmod +x gradlew
      - uses: MeilCli/gradle-update-check-action@v3
        id: outdated
        with:
          build_gradle_files: app/build.gradle.kts
      - uses: github-actions-up-and-running/pr-comment@v1.0.0
        if: steps.outdated.outputs.has_maven_update != 'false'
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message: ${{ steps.outdated.outputs.maven_update_text }}
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}